"""Untimed A4.1.2.3 paired first-generation-logit prefix diagnostic."""

from __future__ import annotations

import argparse
import contextlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import torch
import transformers
from transformers import DynamicCache, pipeline

from kvpress.route_a_measurement import initialize_output_directory, require_cuda_device
from kvpress.route_a_policy_backend import DenseSameMaskAttentionBackend, RouteAColdOwnershipAttentionBackend
from kvpress.route_a_replay import sha256_file
from tools.export_kvzap_predictor_trace import GATE_A_PREDICTOR_REVISION, GATE_B_MODEL_REVISION, assert_no_runtime_mask_state, get_git_commit, stable_hash
from tools.run_kvzap_route_a412_whole_decode_gate import read_source
from tools.run_kvzap_trace import DEFAULT_MODEL, DEFAULT_PREDICTOR, PRESETS, build_builtin_request, load_jsonl_request, seed_everything


A4123_SCHEMA = "kvzap-route-a4123-first-decode-logits-diagnostic-1.0"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="A4.1.2.3 untimed paired first-generation-logit prefix diagnostic; not a benchmark.")
    request = parser.add_mutually_exclusive_group()
    request.add_argument("--preset", choices=PRESETS, default="retrieval")
    request.add_argument("--input-jsonl", type=Path)
    request.add_argument("--request-id")
    parser.add_argument("--context-repetitions", type=int, default=12)
    parser.add_argument("--model-name", default=DEFAULT_MODEL)
    parser.add_argument("--model-revision", default=GATE_B_MODEL_REVISION)
    parser.add_argument("--predictor-name", default=DEFAULT_PREDICTOR)
    parser.add_argument("--predictor-revision", default=GATE_A_PREDICTOR_REVISION)
    parser.add_argument("--threshold", type=float, default=-4.0)
    parser.add_argument("--window-size", type=int, default=128)
    parser.add_argument("--page-tokens", type=int, default=64)
    parser.add_argument("--admission-budget", type=int, required=True)
    parser.add_argument("--target-layer", type=int, required=True)
    parser.add_argument("--target-kv-head", type=int, required=True)
    parser.add_argument("--max-new-tokens", type=int, default=8, help="Must match replay source; no tokens are generated by this diagnostic.")
    parser.add_argument("--top-k", type=int, default=8)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--rtol", type=float, default=1e-4)
    parser.add_argument("--atol", type=float, default=1e-5)
    parser.add_argument("--max-executed-dtype-ulps", type=float, default=16.0)
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--replay-source-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True, help="New output directory only.")
    return parser.parse_args()


def manifest_config(args: argparse.Namespace) -> dict[str, Any]:
    return {key: str(value) if isinstance(value, Path) else value for key, value in vars(args).items() if key != "output_dir"}


def logit_summary(logits: torch.Tensor, *, top_k: int) -> dict[str, Any]:
    """Serialize bounded numeric diagnostics, never the vocabulary-sized logits."""
    if logits.ndim != 1:
        raise ValueError("first-generation logits must be rank one")
    finite = torch.isfinite(logits)
    summary: dict[str, Any] = {
        "vocab_size": int(logits.numel()),
        "all_finite": bool(finite.all().item()),
        "nan_count": int(torch.isnan(logits).sum().item()),
        "positive_inf_count": int(torch.isposinf(logits).sum().item()),
        "negative_inf_count": int(torch.isneginf(logits).sum().item()),
        "argmax_token_id": int(logits.argmax().item()),
    }
    if bool(finite.all().item()):
        values, indices = torch.topk(logits.float(), k=min(top_k, logits.numel()))
        summary["top_tokens"] = [{"token_id": int(index), "logit": float(value)} for value, index in zip(values.tolist(), indices.tolist())]
        summary["top1_top2_margin"] = None if values.numel() < 2 else float(values[0] - values[1])
    else:
        summary["top_tokens"] = None
        summary["top1_top2_margin"] = None
    return summary


def paired_logit_relation(dense: torch.Tensor, route: torch.Tensor) -> dict[str, Any]:
    if dense.shape != route.shape:
        raise ValueError("paired logits have different shapes")
    finite = bool(torch.isfinite(dense).all().item() and torch.isfinite(route).all().item())
    return {
        "same_shape": True,
        "both_all_finite": finite,
        "argmax_token_id_equal": int(dense.argmax().item()) == int(route.argmax().item()),
        "max_abs_difference": None if not finite else float((dense.float() - route.float()).abs().max().item()),
    }


def first_question_forward(*, pipe, context_ids: torch.Tensor, question_ids: torch.Tensor, backend, args: argparse.Namespace) -> torch.Tensor:
    seed_everything(args.seed)
    cache = DynamicCache()
    context = backend if backend is not None else contextlib.nullcontext()
    with torch.no_grad(), context:
        pipe.model.model(input_ids=context_ids, past_key_values=cache)
        positions = torch.arange(int(context_ids.shape[1]), int(context_ids.shape[1]) + int(question_ids.shape[1]), device=pipe.model.device).unsqueeze(0)
        outputs = pipe.model(input_ids=question_ids, past_key_values=cache, position_ids=positions, num_logits_to_keep=1)
    return outputs.logits[0, -1].detach()


def main() -> None:
    args = parse_args()
    if args.output_dir.exists():
        raise FileExistsError(f"output directory already exists: {args.output_dir}")
    if args.request_id is not None and args.input_jsonl is None:
        raise ValueError("--request-id requires --input-jsonl")
    if args.target_layer < 0 or args.target_kv_head < 0 or min(args.context_repetitions, args.page_tokens, args.admission_budget, args.max_new_tokens, args.max_executed_dtype_ulps, args.top_k) <= 0 or args.window_size < 0:
        raise ValueError("invalid first-logit diagnostic dimensions")
    require_cuda_device(args.device)
    if (args.model_name, args.predictor_name, args.model_revision, args.predictor_revision) != (DEFAULT_MODEL, DEFAULT_PREDICTOR, GATE_B_MODEL_REVISION, GATE_A_PREDICTOR_REVISION):
        raise ValueError("first-logit diagnostic is bounded to frozen Qwen3-8B and official MLP revisions")
    request = load_jsonl_request(args.input_jsonl, args.request_id) if args.input_jsonl else build_builtin_request(args.preset, args.context_repetitions)
    print(f"Loading base model: {args.model_name}")
    pipe = pipeline("kv-press-text-generation", model=args.model_name, revision=args.model_revision, device_map="auto", dtype="auto")
    if getattr(pipe.model.config, "_commit_hash", None) != args.model_revision:
        raise ValueError("loaded model revision differs from frozen revision")
    language_model = pipe.model.model.language_model if hasattr(pipe.model.model, "language_model") else pipe.model.model
    if args.target_layer >= len(language_model.layers):
        raise ValueError("target layer is outside the loaded model")
    if args.target_kv_head >= int(language_model.layers[args.target_layer].self_attn.config.num_key_value_heads):
        raise ValueError("target KV head is outside the selected layer")
    layers = (args.target_layer,)
    args.resolved_target_layers = list(layers)
    events, source, event_sha256 = read_source(args.replay_source_dir, args=args, layers=layers)
    tokenized = pipe.preprocess(str(request["context"]), [str(request["question"])], answer_prefix="", max_context_length=pipe.tokenizer.model_max_length, enable_thinking=False)
    context_ids, question_ids = tokenized["context_ids"].to(pipe.model.device), tokenized["questions_ids"][0].to(pipe.model.device)
    if int(context_ids.shape[1]) <= args.window_size:
        raise ValueError("request does not exercise protected hot-window state")
    config = manifest_config(args)
    config["replay_event_file_sha256"] = event_sha256
    initialize_output_directory(args.output_dir, config=config, git_commit=get_git_commit(), record_name="a4123_first_decode_logits_started.json", schema_version=A4123_SCHEMA, boundaries=["Untimed prefix diagnostic: context prefill then one question forward; no greedy decode loop.", "This prefix deliberately does not consume the complete replay source and must not claim full-replay completion.", "It records bounded logits diagnostics only; it is not timing, allocator, HBM, physical-memory, or hardware evidence."])
    print("Pass 1/3: Full-KV bypass first-generation logits...")
    full_logits = first_question_forward(pipe=pipe, context_ids=context_ids, question_ids=question_ids, backend=None, args=args)
    assert_no_runtime_mask_state(pipe.model)
    print("Pass 2/3: same-mask dense control first-generation logits...")
    dense_backend = DenseSameMaskAttentionBackend(pipe.model, None, layer=args.target_layer, kv_head=args.target_kv_head, threshold=args.threshold, window=args.window_size, page_tokens=args.page_tokens, admission_budget=args.admission_budget, rtol=args.rtol, atol=args.atol, max_executed_dtype_ulps=args.max_executed_dtype_ulps, replay_mask_events=events[args.target_layer])
    dense_logits = first_question_forward(pipe=pipe, context_ids=context_ids, question_ids=question_ids, backend=dense_backend, args=args)
    assert_no_runtime_mask_state(pipe.model)
    print("Pass 3/3: owned-cold Route-A first-generation logits...")
    route_backend = RouteAColdOwnershipAttentionBackend(pipe.model, None, layer=args.target_layer, kv_head=args.target_kv_head, threshold=args.threshold, window=args.window_size, page_tokens=args.page_tokens, admission_budget=args.admission_budget, rtol=args.rtol, atol=args.atol, max_executed_dtype_ulps=args.max_executed_dtype_ulps, replay_mask_events=events[args.target_layer])
    route_logits = first_question_forward(pipe=pipe, context_ids=context_ids, question_ids=question_ids, backend=route_backend, args=args)
    assert_no_runtime_mask_state(pipe.model)
    result = {
        "question_token_count": int(question_ids.shape[1]),
        "context_token_count": int(context_ids.shape[1]),
        "full_kv_bypass": logit_summary(full_logits, top_k=args.top_k),
        "same_mask_dense_replay": {"logits": logit_summary(dense_logits, top_k=args.top_k), "policy_decode_calls": dense_backend.policy_decode_calls, "replay_consumption": dense_backend.replay_consumption_summary()},
        "same_mask_route_a_owned_cold_replay": {"logits": logit_summary(route_logits, top_k=args.top_k), "policy_decode_calls": route_backend.policy_decode_calls, "replay_consumption": route_backend.replay_consumption_summary(), "native_cold_ownership": route_backend.ownership_summary()},
        "dense_vs_route": paired_logit_relation(dense_logits, route_logits),
        "full_vs_dense": paired_logit_relation(full_logits, dense_logits),
    }
    manifest = {"schema_version": A4123_SCHEMA, "status": "complete", "created_at": datetime.now(timezone.utc).isoformat(), "git_commit": get_git_commit(), "config": config, "config_hash": stable_hash(config), "request_id": request["request_id"], "request_content_hash": stable_hash({"context": request["context"], "question": request["question"]}), "replay_source": {"directory": str(args.replay_source_dir), "event_file_sha256": event_sha256, "source_manifest_sha256": sha256_file(args.replay_source_dir / "a41_replay_mask_source_manifest.json"), "event_count": source["event_count"]}, "diagnostic": result, "boundaries": ["The question-forward query length determines whether the q_len=1 Route-A decode substitution executes; policy_decode_calls makes that explicit.", "Nonfinite Route-A logits after ownership poisoning identify a native dense fallback that consumed poisoned selected cold K/V; this is a semantic integration finding, not a performance result.", "This is a replay-source prefix diagnostic. It records consumed counts and does not assert complete replay consumption."], "torch_version": str(torch.__version__), "transformers_version": str(transformers.__version__)}
    path = args.output_dir / "a4123_first_decode_logits_manifest.json"
    path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"A4.1.2.3 first-decode logits diagnostic completed: {path}")


if __name__ == "__main__":
    main()
